package com.edu.apiEducation.pessoas;

public enum GrauInstrucao {
	FUNDAMENTAL_INCOMPLETO,
    FUNDAMENTAL_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    POS_GRADUACAO
}
